### ISSUE TITLE
Hardware

### ISSUE THREAD

**Issue by BismarkCT** [rFeijoo/tclab#2]
Acho que faltou colocar a potência dos resistores.

Ficou muito bom o schematico e o layout.

**Comment by rFeijoo** [comment]
Onde?

**Comment by BismarkCT** [comment]
Eu não achei no esquemático

**Comment by rFeijoo** [comment]
Adicionei a *label* ```5W``` nos resistores ```R4``` & ```R8```.

**Comment by rFeijoo** [comment]
Também aproveitei pra aumentar o espaçamento entre as legendas dos pinos (GND, VCC, e IOs) já pensando na montagem... Em que o conector header poderia tampar essas legendas.

**Comment by BismarkCT** [comment]
Blz, vi aqui e me pareceu tudo perfeito
